<%@ Page Language="C#" AutoEventWireup="true" codeFile="course.aspx.cs" Inherits="Expand_Education.course" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script runat="server">

    
</script>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
    <style>
        /* The side navigation menu */
.sidebar {
  margin: 0;
  margin-top:60px;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 86%;
  overflow: auto;
            top: 0px;
            left: 10px;
        }

/* Sidebar links */
.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}

/* Active/current link */
.sidebar a.active {
  background-color: #04AA6D;
  color: white;
}

/* Links on mouse-over */
.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

/* Page content. The value of the margin-left property should match the value of the sidebar's width property */
div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
            margin-top: 0px;
        }

/* On screens that are less than 700px wide, make the sidebar into a topbar */
@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

/* On screens that are less than 400px, display the bar vertically, instead of horizontally */
@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
    
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:Label ID="Label1" runat="server" 
                Font-Bold="True" Font-Italic="True" Font-Size="XX-Large" 
                ForeColor="Yellow" align="center"
                Text="Explore Education                                     " 
            Height="43px" Width="1338px" 
        BackColor="Black" BorderColor="Black" style="margin-bottom: 0px"></asp:Label>

    <!-- The sidebar -->
<div class="sidebar">
  <a class="active" href="#home">Home</a>
  <a href="course.aspx">Courses</a>
  <a href="parentsalltable.aspx">Parents</a>
  <a href="parentsalltable.aspx">Teachers</a>
    <a href="feedback.aspx">Feedback</a>
      <a href="forgotpasswordAdmin.aspx">Change Password</a>
        <a href="Expand Education.aspx">Logout</a>
</div>

<!-- Page content -->
     
        <br />
        <br />
        <br />
        <br />
        <br />
     
        <div class="content">
            <asp:Button ID="Button1" runat="server" Height="42px" style="margin-left: 704px; margin-top: 0px;" 
            Text="Add Course" Width="154px" onclick="Button1_Click" BackColor="#FF6666" 
                Font-Bold="True" Font-Size="Large" />
            <br />
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" Height="254px" 
        style="margin-left: 96px" Width="766px" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" CaptionAlign="Top">
    </asp:GridView>
            <br />
            <br />
            <br />
            <br />
</div>

    </div>
    </form>
</body>
</html>
